# Generated by Django 2.1.7 on 2019-02-28 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.SmallIntegerField()),
                ('title', models.CharField(max_length=100, unique=True)),
                ('genre', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('director', models.CharField(max_length=200)),
                ('actors', models.CharField(max_length=500)),
                ('year', models.SmallIntegerField()),
                ('run_time_minutes', models.SmallIntegerField()),
                ('rating', models.CharField(max_length=10)),
                ('votes', models.CharField(max_length=10)),
                ('revenue_millions', models.CharField(max_length=10)),
                ('meta_score', models.CharField(max_length=10)),
            ],
        ),
    ]
